# Generated by Django 2.0 on 2019-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=50)),
                ('result', models.CharField(default='有效', max_length=2)),
            ],
        ),
    ]
