# Generated by Django 2.0 on 2019-08-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('jurisdiction', models.CharField(max_length=100)),
            ],
        ),
    ]
