# Generated by Django 2.0 on 2019-08-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_num', models.CharField(max_length=20)),
                ('drug_img', models.FileField(upload_to='picture')),
                ('purchasing_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('drug_name', models.CharField(max_length=20)),
                ('drug_type', models.CharField(max_length=20)),
                ('brief_description', models.CharField(max_length=20)),
                ('expiration_time', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('manufacturer', models.CharField(max_length=20)),
                ('taking_instructions', models.TextField()),
                ('inventory', models.IntegerField(default=3000)),
                ('surplus', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=20)),
                ('state', models.CharField(default='未销售', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drup_num', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('not_sent', models.IntegerField()),
                ('principal', models.CharField(max_length=10)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
                ('drug_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Drug')),
            ],
        ),
    ]
