# Generated by Django 2.0 on 2019-08-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_grant',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
