# Generated by Django 2.0 on 2019-08-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_cellectable', models.CharField(max_length=20)),
                ('charge_amount', models.FloatField()),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('all_charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_num', models.IntegerField(null=True)),
                ('cash', models.FloatField()),
                ('into_data', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=20)),
                ('nurse', models.CharField(max_length=30)),
                ('illness', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('certificate_type', models.CharField(max_length=10)),
                ('id_num', models.IntegerField()),
                ('social_security_num', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('self_pay', models.BooleanField(default=False)),
                ('sex', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=10)),
                ('visit', models.CharField(max_length=5)),
                ('money', models.FloatField()),
                ('remark', models.CharField(max_length=100)),
                ('g_time', models.DateField(auto_now_add=True)),
                ('state', models.CharField(max_length=10)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='object_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Charge'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='office_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='charge',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
    ]
