# Generated by Django 2.0 on 2019-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='g_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
