# Generated by Django 2.0 on 2019-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190804_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='g_money',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='certificate_type',
            field=models.CharField(default='身份证', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='g_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='money',
            field=models.FloatField(default=2000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='self_pay',
            field=models.CharField(default='否', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_security_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(default='已挂号', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel',
            field=models.CharField(max_length=20),
        ),
    ]
