# Generated by Django 2.0 on 2019-08-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20190809_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='into_data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
