# Generated by Django 2.0 on 2019-08-11 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_charge_manage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='all_charge',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='charge_amount',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='charge_cellectable',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='charge',
            name='charge_manage_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='hospital.Charge_manage'),
            preserve_default=False,
        ),
    ]
