# Generated by Django 2.0 on 2019-08-11 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20190811_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='charge_cellectable',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
