# Generated by Django 2.0 on 2019-08-11 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_charge_charge_cellectable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='charge_cellectable',
        ),
        migrations.RemoveField(
            model_name='charge_manage',
            name='all_charge',
        ),
        migrations.RemoveField(
            model_name='charge_manage',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='charge',
            name='all_charge',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='exam_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
