# Generated by Django 2.0 on 2019-08-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=10)),
                ('card_type', models.CharField(default='身份证', max_length=15)),
                ('card_num', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('sex', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('birth', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=50)),
                ('in_data', models.DateTimeField(auto_now_add=True)),
                ('d_number', models.IntegerField()),
                ('d_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Departments')),
            ],
        ),
    ]
